name: Build and test

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.14.0'
        otp-version: '25.0.4'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Check for compilation warnings
      run: mix compile --warnings-as-errors
    - name: Check code is formatted
      run: mix format --check-formatted
    - name: Check tests pass
      run: mix test
    - name: Check credo passes
      run: mix credo
    - name: Check dialyzer passes
      run: mix dialyzer
